services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRESQL_ROOT_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_ROOT_DATABASE}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  network_traffic_backend:
    depends_on:
      - postgresdb
    build: 
      context: ./network_traffic_backend
    container_name: network_traffic_backend
    restart: on-failure
    volumes:
      - spring_data:/network_traffic_backend
      - ~/.m2:/root/.m2
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:${POSTGRESQL_DOCKER_PORT}/${POSTGRESQL_ROOT_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${POSTGRESQL_ROOT_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRESQL_ROOT_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

volumes:
  postgres_data:
  spring_data: