spring:
  application:
    name: Backend
  config:
    import:
      - optional:classpath:config/logger.properties
      - optional:classpath:config/jwtsecretkey.properties
  # datasource:
  #   url: ${DOCKER_POSTGRESQL_HOST}${DOCKER_POSTGRESQL_PORT}${DOCKER_POSTGRESQL_DATABASE}
  #   username: ${DOCKER_POSTGRESQL_USERNAME}
  #   password: ${DOCKER_POSTGRESQL_PASSWORD}
  #   driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL}
    hibernate:
        ddl-auto: ${HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: ${JPA_HIBERNATE_FORMAT_SQL}
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# server:
#   port: ${SERVER_PORT}

logging:
  pattern:
    console: ${LOGGER_COMMANDS}
  level:
    org:
      springframework.web: ${LOGGER_LEVEL}
      springframework.web.reactive.function.client.WebClient: ${LOGGER_LEVEL}
      springframework.security: ${LOGGER_LEVEL}
      apache.tomcat.util.http.parser.Cookie: ${LOGGER_LEVEL}

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}