spring:
  profiles:
    active: default
  application:
    name: network_traffic_backend
  config:
    import:
      - optional:classpath:config/abuseapi.properties
      - optional:classpath:config/logger.properties
      - optional:classpath:config/jpaconfig.properties
      - optional:classpath:config/jwttoken.properties
    show-sql: ${JPA_SHOW_SQL}
  jpa:
    hibernate:
        ddl-auto: ${HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: ${JPA_HIBERNATE_FORMAT_SQL}
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  pattern:
    console: ${LOGGER_COMMANDS}
  level:
    org:
      springframework.web: ${LOGGER_LEVEL}
      springframework.web.reactive.function.client.WebClient: ${LOGGER_LEVEL}`
      springframework.security: ${LOGGER_LEVEL}
      springframework.security.web.csrf: ${LOGGER_LEVEL}
      apache.tomcat.util.http.parser.Cookie: ${LOGGER_LEVEL}

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
      refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

abuseip:
  api:
    key: ${ABUSEIP_API_KEY}
    url:
      check: ${ABUSEIP_API_URL_CHECK}
      blacklist: ${ABUSEIP_API_URL_BLACKLIST}