spring:
  application:
    name: network_traffic_backend
  config:
    activate:
      on-profile: development
    import:
      - optional:classpath:config/logger.properties
      - optional:classpath:config/postgresql.properties
      - optional:classpath:config/jpaconfig.properties
      - optional:classpath:config/jwttoken.properties
  datasource:
    url: ${DOCKER_POSTGRESQL_HOST}${DOCKER_POSTGRESQL_PORT}${DOCKER_POSTGRESQL_DATABASE}
    username: ${DOCKER_POSTGRESQL_USERNAME}
    password: ${DOCKER_POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: ${JPA_HIBERNATE_FORMAT_SQL}
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT}

logging:
  pattern:
    console: ${LOGGER_COMMANDS}
  level:
    org:
      springframework.web: ${LOGGER_LEVEL}
      springframework.web.reactive.function.client.WebClient: ${LOGGER_LEVEL}
      springframework.security: ${LOGGER_LEVEL}
      springframework.security.web.csrf: ${LOGGER_LEVEL}
      apache.tomcat.util.http.parser.Cookie: ${LOGGER_LEVEL}

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
      refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}